name: starlight
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'
dependencies: 
  blackfoot_flutter_lint: ^1.0.6
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  get: ^4.6.5
  google_fonts: ^3.0.1
  responsive_framework: ^0.2.0
  velocity_x: ^3.5.1
  flutter: 
    sdk: flutter
  overlapping_panels: ^0.0.3
  adaptive_breakpoints: ^0.1.4
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^0.0.1
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/
  uses-material-design: true
