// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3NRSuVzZMPzhrqSLQXI4jekBvEE2nGM',
    appId: '1:23479163395:web:6a6ccd7433df60cdcc8c36',
    messagingSenderId: '23479163395',
    projectId: 'mob-900-flutter',
    authDomain: 'mob-900-flutter.firebaseapp.com',
    storageBucket: 'mob-900-flutter.appspot.com',
    measurementId: 'G-P1D5CBBB60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACvqRaOhGQz-XMJN7zGakmQIkxdXiNDyo',
    appId: '1:23479163395:android:84e33f8a57aa4674cc8c36',
    messagingSenderId: '23479163395',
    projectId: 'mob-900-flutter',
    storageBucket: 'mob-900-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT9LjkAqURppeqWgX123A8ruWWB4XXSiU',
    appId: '1:23479163395:ios:08b514e3349b898bcc8c36',
    messagingSenderId: '23479163395',
    projectId: 'mob-900-flutter',
    storageBucket: 'mob-900-flutter.appspot.com',
    iosClientId:
        '23479163395-k9i2ts2ld0n60oio9msoq197jhvcghbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.starlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT9LjkAqURppeqWgX123A8ruWWB4XXSiU',
    appId: '1:23479163395:ios:08b514e3349b898bcc8c36',
    messagingSenderId: '23479163395',
    projectId: 'mob-900-flutter',
    storageBucket: 'mob-900-flutter.appspot.com',
    iosClientId:
        '23479163395-k9i2ts2ld0n60oio9msoq197jhvcghbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.starlight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
    measurementId: '',
  );
}
