# This workflow uses actions that are not certified by GitHub.

name: Flutter CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter build appbundle --release
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'
          channel: stable 
      - name: Build web
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref =='refs/heads/main'
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOB_900_FLUTTER }}'
          channelId: live
          projectId: mob-900-flutter
  build-ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'
          channel: stable 
      - name: Build iOS
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter build ios --release --no-codesign
